#!/usr/bin/env perl

package Path::Find::Bin::AccessionFind;

# ABSTRACT: 
# PODNAME: 


BEGIN { unshift( @INC, '../lib' ) }
BEGIN { unshift( @INC, './lib' ) }
BEGIN { unshift( @INC, '/software/pathogen/internal/prod/lib/' ) }

use Path::Find::CommandLine::Accession;

Path::Find::CommandLine::Accession->new(args => \@ARGV, script_name => $0)->run;

__END__

=pod

=encoding UTF-8

=head1 NAME

  -  

=head1 VERSION

version 1.140790

=head1 SYNOPSIS

=head1 AUTHOR

Carla Cummins <cc21@sanger.ac.uk>

=head1 COPYRIGHT AND LICENSE

This software is Copyright (c) 2013 by Wellcome Trust Sanger Institute.

This is free software, licensed under:

  The GNU General Public License, Version 3, June 2007

=cut
